<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_FAQs</name>
   <tag></tag>
   <elementGuidId>753e1cc9-2af8-48d7-b6fa-0ae7bc2e83d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;sc-collapse-navbar&quot;)/nav[1]/div[1]/section[1]/div[@class=&quot;sc-navbar-blocks&quot;]/div[@class=&quot;nav navbar-right&quot;]/ul[@class=&quot;nav navbar-nav&quot;]/li[@class=&quot;hidden-xs&quot;]/a[1][count(. | //a[@title = 'Go to the FAQs page' and @href = '/faqs' and @data-ui-sref = 'public.faqs' and (text() = 'FAQs' or . = 'FAQs')]) = count(//a[@title = 'Go to the FAQs page' and @href = '/faqs' and @data-ui-sref = 'public.faqs' and (text() = 'FAQs' or . = 'FAQs')])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#sc-collapse-navbar</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Go to the FAQs page</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/faqs</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ui-sref</name>
      <type>Main</type>
      <value>public.faqs</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>FAQs</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sc-collapse-navbar&quot;)/nav[1]/div[1]/section[1]/div[@class=&quot;sc-navbar-blocks&quot;]/div[@class=&quot;nav navbar-right&quot;]/ul[@class=&quot;nav navbar-nav&quot;]/li[@class=&quot;hidden-xs&quot;]/a[1]</value>
   </webElementProperties>
</WebElementEntity>
