<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Save_1</name>
   <tag></tag>
   <elementGuidId>8638d59f-ecdb-4b1a-b1a8-b971e0c4e12a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[@title = 'Save' and @type = 'submit' and @data-ng-click = 'vm.institutionEvents.formData.submitted = true' and @class = 'btn btn-success btn-sm pull-right sc-btn-margin-left' and (text() = 'Save' or . = 'Save')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Save</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-click</name>
      <type>Main</type>
      <value>vm.institutionEvents.formData.submitted = true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success btn-sm pull-right sc-btn-margin-left</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Save</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;direct-source&quot;)/div[1]/div[1]/div[@class=&quot;sc-body sc-section-to-print&quot;]/div[1]/div[1]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[2]/div[1]/div[@class=&quot;panel panel-default sc-panel in&quot;]/div[@class=&quot;panel-collapse collapse in&quot;]/div[@class=&quot;panel-body sc-panel-body&quot;]/div[1]/div[2]/div[2]/form[@class=&quot;ng-valid-date ng-dirty ng-valid-parse ng-valid-pattern ng-valid-date-disabled ng-valid ng-valid-required&quot;]/div[@class=&quot;sc-panel-submit-buttons sc-clear-both&quot;]/button[@class=&quot;btn btn-success btn-sm pull-right sc-btn-margin-left&quot;]</value>
   </webElementProperties>
</WebElementEntity>
