<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Cancel</name>
   <tag></tag>
   <elementGuidId>3059a0fe-d859-4a05-8792-e8c52ea1ed1b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;uForm&quot;)/fieldset[1]/div[@class=&quot;pull-right&quot;]/button[@class=&quot;btn btn-default btn-sm pull-right sc-btn-margin-left&quot;][count(. | //button[@type = 'button' and @data-ng-click = concat('vm.$state.go(' , &quot;'&quot; , 'user.customercare.users' , &quot;'&quot; , ');') and @title = 'Cancel' and (text() = 'Cancel' or . = 'Cancel')]) = count(//button[@type = 'button' and @data-ng-click = concat('vm.$state.go(' , &quot;'&quot; , 'user.customercare.users' , &quot;'&quot; , ');') and @title = 'Cancel' and (text() = 'Cancel' or . = 'Cancel')])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-click</name>
      <type>Main</type>
      <value>vm.$state.go('user.customercare.users');</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-disabled</name>
      <type>Main</type>
      <value>vm.user.formData.isFormProcessing</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-default btn-sm pull-right sc-btn-margin-left</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Cancel</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cancel</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;uForm&quot;)/fieldset[1]/div[@class=&quot;pull-right&quot;]/button[@class=&quot;btn btn-default btn-sm pull-right sc-btn-margin-left&quot;]</value>
   </webElementProperties>
</WebElementEntity>
