<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_AlexRepalexrep2example.com</name>
   <tag></tag>
   <elementGuidId>96101085-1afb-4ded-89d5-a351086a3206</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>rowgroup</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-grid-viewport</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-style</name>
      <type>Main</type>
      <value>colContainer.getViewportStyle()</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AlexRepalexrep2@example.comDRS - Alexandria OfficeJul 16, 2018  EditAlexRepalexrep3@example.comDRS - Alexandria OfficeJul 16, 2018  EditAlexRepalexrep4@example.comDRS - Alexandria OfficeJul 16, 2018  EditAlexRepalexrep5@example.comDRS - Alexandria OfficeJul 16, 2018  EditAlexRepalexrep6@example.comDRS - Alexandria OfficeJul 16, 2018  EditAlexRepalexrep7@example.comDRS - Alexandria OfficeJul 16, 2018  EditAlexRepalexrep8@example.comDRS - Alexandria OfficeJul 16, 2018  EditAlexRepalexrep@example.comDRS - Alexandria OfficeJul 16, 2018  EditAlexRepalexrep1@example.comDRS - Alexandria OfficeJul 14, 2018  EditKarenBaughxpd.karen.baugh@dars.virginia.govDRS - Alexandria OfficeJul 03, 2018Feb 08, 2017  EditSuzieMillerxpd.suzie.miller@maryland.govDRS - Alexandria OfficeFeb 08, 2017  EditLapearlSmithxpd.lapearl.smith@dars.virginia.govDRS - Alexandria OfficeFeb 08, 2017  Edit</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;1531757472795-grid-container&quot;)/div[@class=&quot;ui-grid-viewport&quot;]</value>
   </webElementProperties>
</WebElementEntity>
