<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_institution (1)</name>
   <tag></tag>
   <elementGuidId>d5077ec6-fe28-4bb7-accc-83bfa323c8a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;direct-source&quot;)/div[1]/div[1]/div[@class=&quot;sc-body sc-section-to-print&quot;]/div[1]/div[1]/div[@class=&quot;container&quot;]/div[@class=&quot;row sc-content-min-height&quot;]/div[@class=&quot;col-md-12 sc-data-grid-container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;pull-left&quot;]/form[@class=&quot;ng-pristine ng-valid ng-valid-editable&quot;]/div[@class=&quot;form-group sc-uib-typeahead&quot;]/div[1]/input[@class=&quot;form-control sc-users-search-textbox ng-pristine ng-untouched ng-valid ng-valid-editable ng-empty&quot;][count(. | //input[@name = 'institution' and @type = 'text' and @typeahead-editable = 'false']) = count(//input[@name = 'institution' and @type = 'text' and @typeahead-editable = 'false'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>institution</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control sc-users-search-textbox ng-pristine ng-untouched ng-valid ng-valid-editable ng-empty</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>vm.users.formData.institution</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model-options</name>
      <type>Main</type>
      <value>{ debounce: 500, allowInvalid: false }</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>uib-typeahead</name>
      <type>Main</type>
      <value>inst as (inst.externalRefSource+' '+inst.externalRefId+' - '+inst.name) for inst in vm.getInstitutions($viewValue)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>typeahead-editable</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>typeahead-show-hint</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>typeahead-min-length</name>
      <type>Main</type>
      <value>3</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>typeahead-loading</name>
      <type>Main</type>
      <value>vm.users.institutionLoading</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>typeahead-no-results</name>
      <type>Main</type>
      <value>vm.users.institutionNoResults</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>typeahead-on-select</name>
      <type>Main</type>
      <value>vm.selectInstitution($item, $model, $label)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-owns</name>
      <type>Main</type>
      <value>typeahead-760-2663</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;direct-source&quot;)/div[1]/div[1]/div[@class=&quot;sc-body sc-section-to-print&quot;]/div[1]/div[1]/div[@class=&quot;container&quot;]/div[@class=&quot;row sc-content-min-height&quot;]/div[@class=&quot;col-md-12 sc-data-grid-container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;pull-left&quot;]/form[@class=&quot;ng-pristine ng-valid ng-valid-editable&quot;]/div[@class=&quot;form-group sc-uib-typeahead&quot;]/div[1]/input[@class=&quot;form-control sc-users-search-textbox ng-pristine ng-untouched ng-valid ng-valid-editable ng-empty&quot;]</value>
   </webElementProperties>
</WebElementEntity>
